"""empty message

Revision ID: 640a02d3d880
Revises: 62fd1026aa64
Create Date: 2023-01-15 16:58:53.832506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640a02d3d880'
down_revision = '62fd1026aa64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('surname', sa.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
